services:
  my-python-server:
    container_name: my-python-server
    image: python-flask:dev
    working_dir: /app
    volumes:
      - ./code:/app
    command: ["/bin/bash", "-c", "python server.py"]
    ports:
      - 8050:5000